# Generated by Django 3.2.24 on 2024-02-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='modified',
        ),
    ]
